branches:
  only:
    - master
    
install:
  - set QTDIR=C:\Qt\5.13\mingw73_32
  - set QT_TOOLS_DIR=C:\Qt\Tools\mingw730_32
  - set PATH=%QTDIR%\bin;%QT_TOOLS_DIR%\bin;%PATH%
  
build_script:
  - cd ./ColorLinesMultigame
  - qmake ColorLinesMultigame.pro
  - mingw32-make
  
after_build:
  - ls
  - cd ../
  - ls
  - windeployqt bin/ColorLinesMultigame.exe
  - mv bin ColorLines

#Note: artifacts path should be from root directory
artifacts:
  - path: ColorLines
    type: zip
