language: cpp

compiler:
  - gcc
  - clang
  
install:
  - sudo apt-get update
  - sudo apt install qt5-default qtbase5-dev

script:
  - cd ./ColorLinesMultigame
  - qmake ColorLinesMultigame.pro
  - make
  - cd ../ClickLines
  - qmake ClickLines.pro
  - make
  - cd ../Lines
  - qmake ColorLines.pro
  - make
  - cd ../Snake
  - qmake Snake.pro
  - make
  - cd ../Tetris
  - qmake Tetris.pro
  - make

